package sparse::sym::SYM_UNINITIALIZED;
our @ISA = qw (sparse::sym);
package sparse::sym::SYM_PREPROCESSOR;
our @ISA = qw (sparse::sym);
package sparse::sym::SYM_BASETYPE;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_NODE;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_PTR;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_FN;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_ARRAY;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_STRUCT;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_UNION;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_ENUM;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_TYPEDEF;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_TYPEOF;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_MEMBER;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_BITFIELD;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_LABEL;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_RESTRICT;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_FOULED;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_KEYWORD;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
package sparse::sym::SYM_BAD;
our @ISA = qw (sparse::sym sparse::sym::NS_SYMBOL);
1;

